/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package repaso.tarea4calculadoramiguelangel;

import java.awt.List;
import java.util.ArrayList;

/**
 *
 * @author miguel
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCalc = new javax.swing.JPanel();
        bonton1 = new javax.swing.JButton();
        bonton2 = new javax.swing.JButton();
        bonton4 = new javax.swing.JButton();
        bonton3 = new javax.swing.JButton();
        bonton5 = new javax.swing.JButton();
        bonton6 = new javax.swing.JButton();
        bonton7 = new javax.swing.JButton();
        bonton8 = new javax.swing.JButton();
        bonton9 = new javax.swing.JButton();
        bonton0 = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        botonMultiplicacion = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        botonCBorrarTodo = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        jPanelPantalla = new javax.swing.JPanel();
        labelPantalla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCalc.setForeground(new java.awt.Color(153, 153, 153));

        bonton1.setText("1");
        bonton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton1MouseClicked(evt);
            }
        });

        bonton2.setText("2");
        bonton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton2MouseClicked(evt);
            }
        });

        bonton4.setText("4");
        bonton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton4MouseClicked(evt);
            }
        });

        bonton3.setText("3");
        bonton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton3MouseClicked(evt);
            }
        });

        bonton5.setText("5");
        bonton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton5MouseClicked(evt);
            }
        });

        bonton6.setText("6");
        bonton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton6MouseClicked(evt);
            }
        });

        bonton7.setText("7");
        bonton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton7MouseClicked(evt);
            }
        });

        bonton8.setText("8");
        bonton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton8MouseClicked(evt);
            }
        });
        bonton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton8ActionPerformed(evt);
            }
        });

        bonton9.setText("9");
        bonton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton9MouseClicked(evt);
            }
        });

        bonton0.setText("0");
        bonton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bonton0MouseClicked(evt);
            }
        });
        bonton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bonton0ActionPerformed(evt);
            }
        });

        botonSuma.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        botonSuma.setText("+");
        botonSuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSumaMouseClicked(evt);
            }
        });
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });

        botonResta.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        botonResta.setText("-");
        botonResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRestaMouseClicked(evt);
            }
        });

        botonMultiplicacion.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        botonMultiplicacion.setText("*");
        botonMultiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMultiplicacionMouseClicked(evt);
            }
        });
        botonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicacionActionPerformed(evt);
            }
        });

        botonDivision.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        botonDivision.setText("/");
        botonDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDivisionMouseClicked(evt);
            }
        });

        botonCBorrarTodo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        botonCBorrarTodo.setText("c");
        botonCBorrarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCBorrarTodoMouseClicked(evt);
            }
        });

        botonIgual.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonIgualMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCalcLayout = new javax.swing.GroupLayout(jPanelCalc);
        jPanelCalc.setLayout(jPanelCalcLayout);
        jPanelCalcLayout.setHorizontalGroup(
            jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcLayout.createSequentialGroup()
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalcLayout.createSequentialGroup()
                        .addComponent(bonton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bonton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bonton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCalcLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bonton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bonton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bonton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalcLayout.createSequentialGroup()
                        .addComponent(bonton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bonton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bonton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bonton0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalcLayout.createSequentialGroup()
                        .addComponent(botonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCalcLayout.createSequentialGroup()
                        .addComponent(botonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanelCalcLayout.setVerticalGroup(
            jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonton0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bonton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bonton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bonton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        labelPantalla.setText(" ");

        javax.swing.GroupLayout jPanelPantallaLayout = new javax.swing.GroupLayout(jPanelPantalla);
        jPanelPantalla.setLayout(jPanelPantallaLayout);
        jPanelPantallaLayout.setHorizontalGroup(
            jPanelPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantallaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelPantallaLayout.setVerticalGroup(
            jPanelPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPantallaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bonton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton8ActionPerformed
        
    }//GEN-LAST:event_bonton8ActionPerformed

    private void bonton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bonton0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bonton0ActionPerformed

    private void botonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMultiplicacionActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSumaActionPerformed

    private void bonton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton7MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"7");
    }//GEN-LAST:event_bonton7MouseClicked

    private void bonton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton1MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"1");
    }//GEN-LAST:event_bonton1MouseClicked

    private void bonton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton2MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"2");
    }//GEN-LAST:event_bonton2MouseClicked

    private void bonton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton3MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"3");
    }//GEN-LAST:event_bonton3MouseClicked

    private void bonton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton4MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"4");
    }//GEN-LAST:event_bonton4MouseClicked

    private void bonton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton5MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"1");
    }//GEN-LAST:event_bonton5MouseClicked

    private void bonton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton6MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"6");
    }//GEN-LAST:event_bonton6MouseClicked

    private void bonton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton8MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"8");
    }//GEN-LAST:event_bonton8MouseClicked

    private void bonton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton9MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"9");
    }//GEN-LAST:event_bonton9MouseClicked

    private void bonton0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bonton0MouseClicked
        labelPantalla.setText(labelPantalla.getText()+"0");
    }//GEN-LAST:event_bonton0MouseClicked

    private void botonSumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSumaMouseClicked
       labelPantalla.setText(labelPantalla.getText()+" + ");
    }//GEN-LAST:event_botonSumaMouseClicked

    private void botonRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRestaMouseClicked
        labelPantalla.setText(labelPantalla.getText()+" - ");
    }//GEN-LAST:event_botonRestaMouseClicked

    private void botonMultiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMultiplicacionMouseClicked
        labelPantalla.setText(labelPantalla.getText()+" * ");
    }//GEN-LAST:event_botonMultiplicacionMouseClicked

    private void botonDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDivisionMouseClicked
        labelPantalla.setText(labelPantalla.getText()+" / ");
    }//GEN-LAST:event_botonDivisionMouseClicked

    private void botonCBorrarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCBorrarTodoMouseClicked
        labelPantalla.setText("");
    }//GEN-LAST:event_botonCBorrarTodoMouseClicked

    private void botonIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIgualMouseClicked
        
        if (labelPantalla.getText().contains("+")) {
            
        } else if(labelPantalla.getText().contains("-")){
            
        } else if(labelPantalla.getText().contains("*")){
        
        } else if(labelPantalla.getText().contains("/")){
        
        } else {
        }
    }//GEN-LAST:event_botonIgualMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    
    public void suma(int num1, int num2){
        
        int resultado = num1 + num2;
        labelPantalla.setText(" " + resultado);
    }
    
    public void resta(int num1, int num2){
        
        int resultado = num1 - num2;
        labelPantalla.setText(" " + resultado);
    }
    
    public void mult(int num1, int num2){
        
        int resultado = num1 * num2;
        labelPantalla.setText(" " + resultado);
    }
    
    public void div(int num1, int num2){
        
        double resultado = num1 / num2;
        labelPantalla.setText(" " + resultado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bonton0;
    private javax.swing.JButton bonton1;
    private javax.swing.JButton bonton2;
    private javax.swing.JButton bonton3;
    private javax.swing.JButton bonton4;
    private javax.swing.JButton bonton5;
    private javax.swing.JButton bonton6;
    private javax.swing.JButton bonton7;
    private javax.swing.JButton bonton8;
    private javax.swing.JButton bonton9;
    private javax.swing.JButton botonCBorrarTodo;
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMultiplicacion;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSum;
    private javax.swing.JButton botonSuma;
    private javax.swing.JPanel jPanelCalc;
    private javax.swing.JPanel jPanelPantalla;
    private javax.swing.JTextField labelPantalla;
    // End of variables declaration//GEN-END:variables
}
